CREATE DATABASE ESTACIONAMENTO;
USE ESTACIONAMENTO;

CREATE TABLE CLIENTE(
CNH INT(12) AUTO_INCREMENT NOT NULL,
NOME VARCHAR(45) NOT NULL,
TELEFONE INT NOT NULL,
DT_VENCIMENTO DATE NOT NULL,
PRIMARY KEY(CNH)
);

INSERT INTO CLIENTE(CNH,NOME,TELFONE,DT_VENCIMENTO)
VALUES(NULL, 'NOME', 00000000000, 20001231 );


CREATE TABLE VEICULO(
PLACA VARCHAR(6) NOT NULL,
MODELO VARCHAR(25) NOT NULL,
PRIMARY KEY(PLACA)
);

INSERT INTO VEICULO(PLACA, MODELO)
VALUES('AAA000', ' MODELO VEICULO ');

CREATE TABLE PAGAMENTO(
TIPO VARCHAR(6) NOT NULL,
PAGAMENTO INT(40) NOT NULL,
CLIENTE_CNH INT(12) NOT NULL,
VALORES_VALOR DOUBLE(9,2) NOT NULL,
VEICULO_PLACA VARCHAR(6) NOT NULL, 
VEICULO_MODELO VARCHAR(25) NOT NULL,
PRIMARY KEY(TIPO),
FOREIGN KEY(CLIENTE_CNH) REFERENCES CLIENTE(CNH),
FOREIGN KEY(VALORES_VALOR) REFERENCES VALORES(VALOR),
FOREIGN KEY(VEICULO_PLACA) REFERENCES VEICULO(PLACA),
FOREIGN KEY(VEICULO_MODELO) REFERENCES VEICULO(MODELO)
);

INSERT INTO PAGAMENTO(TIPO, PAGAMENTO, CLIENTE_CNH, VALORES_VALOR, VEICULO_PLACA, VEICULO_MODELO)
VALUES('TIPO', 00, 000000000000, 00.00, 'AAA000', ' MODELO VEICULO ');

CREATE TABLE VALORES(
VALOR DOUBLE(9,2) NOT NULL,
HORISTA DOUBLE(9,2) NOT NULL,
MENSALISTA DOUBLE(9,2) NOT NULL
);

INSERT INTO VALORES(VALOR, HORISTA, MENSALISTA)
VALUES( 00.00, 00.00, 00.00);

CREATE TABLE PAGAMENTO_HORISTA(
ENTRADA VARCHAR(45) NOT NULL,
SAIDA VARCHAR(45) NOT NULL,
PAGAMENTO_PAGAMENTO INT(40) NOT NULL,
PRIMARY KEY(ENTRADA),
FOREIGN KEY(PAGAMENTO_PAGAMENTO) REFERENCES PAGAMENTO(PAGAMENTO)
);

INSERT INTO PAGAMENTO_HORISTA(ENTRADA, SAIDA, PAGAMENTO_PAGAMENTO)
VALUES(' ENTRADA ', ' SAIDA ', 00 );

CREATE TABLE PAGAMENTO_MENSALISTA(
MES_REF VARCHAR(45) NOT NULL,
DT_PAGAMENTO DATE NOT NULL,
PRIMARY KEY(MES_REF)
);

INSERT INTO PAGAMENTO_MENSALISTA(MES_REF,DT_PAGAMENTO)
VALUES('MES' , 20001231 );